include $(LITEOSTOPDIR)/config.mk

MODULE_NAME := screw

LOCAL_SRCS  := \
        $(wildcard src/*.c) \
        $(LITEOSTOPDIR)/../../third_party/FreeBSD/sys/libkern/crc32.c

include $(MODULE)
